name: Publish

on:
  push:
    branches: [ try-import ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - name: report
      run: |
        python -m pydicom.env_info
